spring.application.name=clinica
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_veterinaria
spring.datasource.username=postgres
spring.datasource.password=Admin123

# JWT (la clave debe tener al menos 32 caracteres)
jwt.secret=k8X9mP2vL4qW7zR1fY5bH3nJ6dC0sF8t
jwt.expiration=86400000